stages:
  - code_style
  - build
  - deploy

variables:
  DIMIGOIN_REGISTRY: docker-registry.dimigo.in
  IMAGE_NAME: echo-back
  PRO_IMAGE_TAG: $DIMIGOIN_REGISTRY/$IMAGE_NAME:production
  DEV_IMAGE_TAG: $DIMIGOIN_REGISTRY/$IMAGE_NAME:dev

prettier:
    image: node
    stage: code_style
    script:
      - npm i prettier -g
      - prettier --check "**/*.js"

docker-build:
  image: docker:latest
  stage: build
  script:
    - docker build -t $PRO_IMAGE_TAG -t $DEV_IMAGE_TAG .
  tags:
    - main

dev-deploy:
 image: docker:latest
 stage: deploy
 only:
    - develop
 script:
    - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD $DIMIGOIN_REGISTRY
    - docker push $DEV_IMAGE_TAG
 environment:
    name: test
    url: https://dev-api.echo.dimigo.in
 tags:
    - main

production-deploy:
  image: docker:latest
  stage: deploy
  only:
    - master
  when: manual
  script:
    - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD $DIMIGOIN_REGISTRY
    - docker push $PRO_IMAGE_TAG
  environment:
    name: test
    url: https://api.echo.dimigo.in
  tags:
    - main
